version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.6.0
    steps:
      - checkout
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: npm test


